name: Java CI con Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Descargar codigo
      uses: actions/checkout@v3

    - name: 2. Configurar Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: 3. Ejecutar Tests y Generar JAR
      run: mvn -B package --file vib_ED_pt2/pom.xml

    - name: 4. Subir JAR (Artefacto)
      uses: actions/upload-artifact@v3
      with:
          name: vib_ED_tests-jar
          path: vib_ED_pt2/target/*.jar
