name: Java CI con Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Descargar codigo
      uses: actions/checkout@v3

    - name: 2. Configurar Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: 3. Ejecutar Tests y Generar JAR
      # Buscamos el pom.xml donde quiera que este
      run: |
        POM_PATH=$(find . -name "pom.xml" | head -n 1)
        DIR_PATH=$(dirname $POM_PATH)
        mvn -B package --file $POM_PATH
        echo "JAR_DIR=$DIR_PATH/target" >> $GITHUB_ENV

    - name: 4. Subir JAR (Artefacto)
      uses: actions/upload-artifact@v3
      with:
          name: vib_ED_tests-jar
          path: "**/*.jar"
